-- =============================================================================
-- SPRINT 3: DATABASE MIGRATION - GAMIFICATION, POINTS & LUCKY DRAW SCHEMA
-- TARGET: PostgreSQL 15+
-- DESCRIPTION: Core gamification activity rules, participant profiles, points balance tracking,
--              double-entry ledger with triggers, prizes inventory, and lucky draw winners.
-- =============================================================================

BEGIN;

-- 1. Create Companies Table
CREATE TABLE IF NOT EXISTS companies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(150) NOT NULL UNIQUE,
    industry VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Create Participants Table (with points)
CREATE TABLE IF NOT EXISTS participants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies(id) ON DELETE SET NULL,
    table_id UUID, -- references event_tables(id) on full schema
    seat_number INT CONSTRAINT check_seat_number CHECK (seat_number > 0),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(30),
    position VARCHAR(100),
    avatar_url VARCHAR(512),
    qr_code_hash VARCHAR(64) NOT NULL UNIQUE,
    checked_in BOOLEAN NOT NULL DEFAULT FALSE,
    checked_in_at TIMESTAMPTZ,
    current_points INT NOT NULL DEFAULT 0 CONSTRAINT check_min_points CHECK (current_points >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_checked_in_timestamp CHECK (
        (checked_in = FALSE AND checked_in_at IS NULL) OR 
        (checked_in = TRUE AND checked_in_at IS NOT NULL)
    ),
    CONSTRAINT unique_table_seat UNIQUE (table_id, seat_number)
);

-- 3. Create Activity Rules Definition
CREATE TABLE IF NOT EXISTS activity_rules (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_type VARCHAR(50) NOT NULL UNIQUE,
    points_reward INT NOT NULL CONSTRAINT check_reward_points CHECK (points_reward > 0),
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed Initial System Rules
INSERT INTO activity_rules (activity_type, points_reward, description) VALUES
('CHECK_IN', 5, 'Points granted upon dynamic QR or manual staff check-in.'),
('SUBMIT_FEEDBACK', 5, 'Guest submits qualitative event feedback form.'),
('SHARE_PHOTO', 5, 'Guest uploads photo proof of attendance or task.'),
('INSTAGRAM_POST', 5, 'Guest shares story/post with event hashtag.'),
('SONG_REQUEST', 5, 'Awarded points upon a song request approval.'),
('VIP_REGISTRATION', 10, 'Bonus award granted to designated key VIP profiles.')
ON CONFLICT (activity_type) DO NOTHING;

-- 4. Create Activity Submissions (Gamification Proofs)
CREATE TABLE IF NOT EXISTS activity_submissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    participant_id UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    activity_rule_id INT NOT NULL REFERENCES activity_rules(id) ON DELETE RESTRICT,
    submission_text TEXT,
    submission_media_url VARCHAR(512),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CONSTRAINT check_submission_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    reviewed_by VARCHAR(100),
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. Create Point Transaction Ledger (Double-Entry Balance Integrity)
CREATE TABLE IF NOT EXISTS point_transactions_ledger (
    id BIGSERIAL PRIMARY KEY,
    participant_id UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    submission_id UUID REFERENCES activity_submissions(id) ON DELETE SET NULL,
    points_changed INT NOT NULL CONSTRAINT check_points_changed CHECK (points_changed <> 0),
    running_balance INT NOT NULL CONSTRAINT check_running_balance CHECK (running_balance >= 0),
    reason VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 6. Create Prize Categories & System Tiers (Lucky Draw Tiers)
CREATE TABLE IF NOT EXISTS prize_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(50) NOT NULL UNIQUE,
    eligible_points_min INT NOT NULL DEFAULT 0 CONSTRAINT check_eligible_points CHECK (eligible_points_min >= 0),
    tier_level INT NOT NULL UNIQUE CONSTRAINT check_tier_level CHECK (tier_level >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed Standard Tiers
INSERT INTO prize_categories (name, eligible_points_min, tier_level) VALUES
('Bronze Tier Selections', 0, 1),
('Silver Tier Selections', 11, 2),
('Gold Tier Selections', 21, 3)
ON CONFLICT (name) DO NOTHING;

-- 7. Create Prizes Inventory
CREATE TABLE IF NOT EXISTS prizes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id UUID NOT NULL REFERENCES prize_categories(id) ON DELETE RESTRICT,
    name VARCHAR(100) NOT NULL,
    total_quantity INT NOT NULL CONSTRAINT check_total_qty CHECK (total_quantity >= 0),
    remaining_quantity INT NOT NULL CONSTRAINT check_remaining_qty CHECK (remaining_quantity >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_qty_bounds CHECK (remaining_quantity <= total_quantity)
);

-- 8. Create Lucky Draw Winners
CREATE TABLE IF NOT EXISTS lucky_draw_winners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    participant_id UUID NOT NULL REFERENCES participants(id) ON DELETE RESTRICT,
    prize_id UUID NOT NULL REFERENCES prizes(id) ON DELETE RESTRICT,
    drawn_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Strict Rule: One participant can win at most one prize in the entire event
    CONSTRAINT unique_one_prize_per_guest UNIQUE (participant_id)
);

-- 9. Create Song Requests Board
CREATE TABLE IF NOT EXISTS song_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    participant_id UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    artist VARCHAR(100) NOT NULL,
    title VARCHAR(150) NOT NULL,
    message TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CONSTRAINT check_song_status CHECK (status IN ('PENDING', 'APPROVED', 'PLAYED', 'REJECTED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 10. Create Notifications
CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    participant_id UUID NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 11. Create Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGSERIAL PRIMARY KEY,
    actor_id VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL,
    action VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL CONSTRAINT check_log_severity CHECK (severity IN ('INFO', 'SUCCESS', 'WARNING', 'ERROR')),
    details TEXT NOT NULL,
    metadata JSONB,
    ip_address VARCHAR(45),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- INDEXING OPTIMIZATIONS
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_participants_qr ON participants (qr_code_hash) WHERE checked_in = FALSE;
CREATE INDEX IF NOT EXISTS idx_participants_points_leaderboard ON participants (checked_in, current_points DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_pending_moderation ON activity_submissions (status) WHERE status = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_point_ledger_lookup ON point_transactions_ledger (participant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_songs_pending_dashboard ON song_requests (status, created_at ASC) WHERE status = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications (participant_id) WHERE is_read = FALSE;
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit_logs (timestamp DESC);

-- ==========================================
-- DOUBLE-ENTRY LEDGER INTEGRITY TRIGGER
-- ==========================================
CREATE OR REPLACE FUNCTION update_participant_points_from_ledger()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE participants
    SET current_points = current_points + NEW.points_changed
    WHERE id = NEW.participant_id;

    -- Safety check: ensure points never drop below zero
    IF EXISTS (SELECT 1 FROM participants WHERE id = NEW.participant_id AND current_points < 0) THEN
        RAISE EXCEPTION 'Ledger transaction failed: point balance cannot drop below zero.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_on_ledger_insert
AFTER INSERT ON point_transactions_ledger
FOR EACH ROW
EXECUTE FUNCTION update_participant_points_from_ledger();

COMMIT;
